# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.IntegerField()),
                ('plantName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSearchOccur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=50)),
                ('occurance', models.IntegerField()),
            ],
        ),
    ]
